name: "Build"
on:
  pull_request:
  push:
  schedule:
    - cron: '55 */6 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      if: runner.os == 'Linux'
      uses: mio-19/maximize-build-space@751b517c9f4fa92ff0da312d413d6abf01ff5ed3 # patch-1
      with:
        root-reserve-mb: 1024
        swap-size-mb: 18000
        overprovision-lvm: 'true'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        build-mount-path: /nix
    - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
    - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= mio.cachix.org-1:FlupyyLPURqwdRqtPT/LBWKsXY7JKsDkzZQo2K6LeMM= mio-cache.cachix.org-1:ouuIJZ59HIflYjpLW6DRyMc1c+6r3kC/LHuqGUsWigg= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= staging.cachix.org-1:WX63nyFdVdWGn6n59pIYwkcH/AtjJGjvMQFKlI2z00w= niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g=
          substituters = https://cache.nixos.org/ https://mio.cachix.org/ https://mio-cache.cachix.org/ https://cache.garnix.io https://nix-community.cachix.org/ https://staging.cachix.org/ https://cache.numtide.com
    - uses: cachix/cachix-action@02b16339eddcf6ea27126a830c7f1992855cae13 # v17
      with:
        name: mio-config
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: (cd nixos && timeout --signal=KILL 20m nix build .#nixosConfigurations.ipc.config.system.build.toplevel --keep-going --max-jobs 1 --option core 1)
      continue-on-error: true
    - run: (cd nixos && timeout --signal=KILL 20m nix build .#nixosConfigurations.fw13.config.system.build.toplevel --keep-going --max-jobs 1 --option core 1)
      continue-on-error: true
    - run: (cd nixos && timeout --signal=KILL 20m nix build .#nixosConfigurations.deck.config.system.build.toplevel --keep-going --max-jobs 1 --option core 1)
      continue-on-error: true
    - run: (cd nixos && nix flake update && timeout --signal=KILL 20m nix build .#nixosConfigurations.ipc.config.system.build.toplevel --keep-going --max-jobs 1 --option core 1)
      continue-on-error: true
    - run: (cd nixos && nix flake update && timeout --signal=KILL 20m nix build .#nixosConfigurations.fw13.config.system.build.toplevel --keep-going --max-jobs 1 --option core 1)
      continue-on-error: true
    - run: (cd nixos && nix flake update && timeout --signal=KILL 20m nix build .#nixosConfigurations.deck.config.system.build.toplevel --keep-going --max-jobs 1 --option core 1)
      continue-on-error: true
    - run: (cd nixos && nix flake update --override-input nixpkgs-unstable github:nixos/nixpkgs/master && timeout --signal=KILL 20m nix build .#nixosConfigurations.ipc.config.system.build.toplevel --keep-going --max-jobs 1 --option core 1)
      continue-on-error: true
    - run: (cd nixos && nix flake update --override-input nixpkgs-unstable github:nixos/nixpkgs/master && timeout --signal=KILL 20m nix build .#nixosConfigurations.fw13.config.system.build.toplevel --keep-going --max-jobs 1 --option core 1)
      continue-on-error: true
    - run: (cd nixos && nix flake update --override-input nixpkgs-unstable github:nixos/nixpkgs/master && timeout --signal=KILL 20m nix build .#nixosConfigurations.deck.config.system.build.toplevel --keep-going --max-jobs 1 --option core 1)
      continue-on-error: true
