name: nixbuild
on: push
# https://github.com/nixbuild/nixbuild-action
jobs:
  checks:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v24
    with:
      filter_builds: '.top_attr == "nixosConfigurations"'
      flake: './nixos'
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}